language: crystal
os:
  - linux
  - osx

install: |
  if [ $TRAVIS_OS_NAME = "linux" ]
  then
    docker build --tag batch .
  fi

script:
  - make build
  # https://github.com/crystal-lang/crystal/issues/8075
  # - make test
  - |
    if [ $TRAVIS_OS_NAME = "linux" ]
    then
      rm -f bin/batch && docker run --rm --mount "type=bind,source=$PWD,destination=/app" batch
    fi
  - tar -C bin -czf batch-$TRAVIS_TAG-x86_64-$TRAVIS_OS_NAME.tar.gz batch

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: 
    - batch-*.tar.gz
  skip_cleanup: true
  on:
    tags: true
