# GitHub Actions
# https://github.com/features/actions

# GitHub CLI
# https://cli.github.com

name: Test CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run tests
        run: scripts/docker-run make build test
